-- Baseline schema matching JPA entities under com.ywes.application_tracker.model

CREATE TABLE users (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(20)  NOT NULL,
    password    VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE refresh_token (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      INTEGER      NOT NULL,
    token        VARCHAR(255) NOT NULL,
    expiry_date  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_refresh_token_user_id UNIQUE (user_id),
    CONSTRAINT uk_refresh_token_token UNIQUE (token),
    CONSTRAINT fk_refresh_token_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE job_application (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          INTEGER       NOT NULL,
    company          VARCHAR(255)  NOT NULL,
    role             VARCHAR(255)  NOT NULL,
    status           VARCHAR(255)  NOT NULL,
    notes            VARCHAR(255),
    job_posting_url  VARCHAR(2048),
    created_at       TIMESTAMP(6)  NOT NULL,
    updated_at       TIMESTAMP(6)  NOT NULL,
    CONSTRAINT fk_job_application_user
        FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE board_placement (
    application_id  INTEGER      NOT NULL PRIMARY KEY,
    user_id         INTEGER      NOT NULL,
    status          VARCHAR(255) NOT NULL,
    position        INTEGER      NOT NULL,
    CONSTRAINT uc_user_status_position UNIQUE (user_id, status, position),
    CONSTRAINT fk_board_placement_application
        FOREIGN KEY (application_id) REFERENCES job_application (id)
);
