spring.datasource.url=jdbc:postgresql://localhost:5432/application-tracker
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto=validate
spring.h2.console.enabled=false
spring.flyway.enabled=true