spring.application.name=application-tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/application-tracker
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto=update