security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in millisecond
security.jwt.expiration-time=3600000
# 1 day in millisecond
security.refresh.expiration-time=86400000
security.refresh.cookie-name=refresh_token
security.refresh.cookie-path=/api/auth
security.refresh.cookie-secure=false
security.refresh.cookie-same-site=None

logging.level.org.springframework.security=TRACE

app.cors.allowed-origins=http://localhost:5173,http://localhost:80