# 15min in millisecond
security.jwt.expiration-time=900000
# 1 week in millisecond
security.refresh.expiration-time=604800000
security.refresh.cookie-name=refresh_token
security.refresh.cookie-path=/api/auth
security.refresh.cookie-secure=true
security.refresh.cookie-same-site=Lax

logging.level.org.springframework.security=INFO

spring.sql.init.mode=never
spring.jpa.show-sql = false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.defer-datasource-initialization=false
spring.h2.console.enabled=false
spring.flyway.enabled=true