spring.datasource.url=jdbc:postgresql://localhost:5432/application-tracker
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.sql.init.mode=never
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.defer-datasource-initialization=false
spring.h2.console.enabled=false
spring.flyway.enabled=true